### ISSUE TITLE
Request for 3.10 wheels published to pypi

### ISSUE THREAD

**Issue by akursar** [escherba/python-cityhash#70]
I see cp310 was added to publish.yml here https://github.com/escherba/python-cityhash/commit/71c009717651b9ffeb48720295be15a4488c5581 but there are no 3.10 wheels listed at https://pypi.org/project/cityhash/#files

Additionally, when i try to `pip install cityhash` on `aarch64` the wheel build fails with `gcc: error: unrecognized command-line option ‘-maes’`

Looking to be able to install cityhash on `aarch64`, ideally with wheels, but being able to do a source install would work too :)

**Comment by akursar** [comment]
To be clear, I am trying to do this on apple arm:

    docker run --rm --platform linux/aarch64 python:3.10 pip install cityhash

which fails. I can work around by setting the same env var as the ci build:

    docker run --rm -e AUDITWHEEL_ARCH=aarch64 --platform linux/aarch64 python:3.10 pip install cityhash

but ideally I wouldn't need to do that, and best would be if that installed a wheel :)

**Comment by escherba** [comment]
Thank you very much for your detailed report. I fixed the AARCH64 build issue, and the command you listed should now succeed (tested with Docker on Apple M1):
```
docker run --rm --platform linux/aarch64 python:3.10 pip install cityhash
Collecting cityhash
  Downloading cityhash-0.4.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.2/294.2 kB 2.3 MB/s eta 0:00:00
Installing collected packages: cityhash
Successfully installed cityhash-0.4.2
```
The Python-3.10 wheels also now show up at https://pypi.org/project/cityhash/0.4.2/#files.

Closing this issue but feel free to re-open if my fix was not complete and you still experience the problem.
