### ISSUE TITLE
Not install with python 3.11

### ISSUE THREAD

**Issue by itpooh** [escherba/python-cityhash#73]
In MacOS, python 3.11

Collecting cityhash
  Using cached cityhash-0.4.2.tar.gz (215 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: cityhash
  Building wheel for cityhash (pyproject.toml): started
  Building wheel for cityhash (pyproject.toml): finished with status 'error'
Failed to build cityhash

  error: subprocess-exited-with-error
  
  × Building wheel for cityhash (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      system: posix-64
      available CPU flags: ['1gbpage', '3dnowprefetch', 'abm', 'acpi', 'adx', 'aes', 'apic', 'avx', 'avx1.0', 'avx2', 'bmi1', 'bmi2', 'clflush', 'clflushopt', 'clfsh', 'clfsopt', 'cmov', 'cx16', 'cx8', 'de', 'ds', 'ds_cpl', 'dscpl', 'dtes64', 'dts', 'em64t', 'erms', 'est', 'f16c', 'fma', 'fpu', 'fpu_csds', 'fxsr', 'ht', 'htt', 'ibrs', 'intel_pt', 'invpcid', 'ipt', 'l1df', 'lahf', 'lahf_lm', 'lzcnt', 'mca', 'mce', 'mdclear', 'mmx', 'mon', 'monitor', 'movbe', 'mpx', 'msr', 'mtrr', 'osxsave', 'pae', 'pat', 'pbe', 'pcid', 'pclmulqdq', 'pdcm', 'pge', 'pni', 'popcnt', 'prefetchw', 'pse', 'pse36', 'rdrand', 'rdrnd', 'rdseed', 'rdtscp', 'rdwrfsgs', 'seglim64', 'sep', 'sgx', 'sgx_lc', 'sgxlc', 'smap', 'smep', 'ss', 'ssbd', 'sse', 'sse2', 'sse3', 'sse4.1', 'sse4.2', 'sse4_1', 'sse4_2', 'ssse3', 'stibp', 'syscall', 'tm', 'tm2', 'tpr', 'tsc', 'tsc_thread_offset', 'tscdeadline', 'tsci', 'tsctmr', 'tsxfa', 'vme', 'vmx', 'x2apic', 'xd', 'xsave', 'xtpr']
      environment: PATH=/private/var/folders/by/pdgmdm4d6cd0pcl85wrh27vngtsnyj/T/pip-build-env-3i9wshe2/overlay/bin:/private/var/folders/by/pdgmdm4d6cd0pcl85wrh27vngtsnyj/T/pip-build-env-3i9wshe2/normal/bin:/Users/aazhiry1/venvs/cmd_bl_311_2/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin, __CFBundleIdentifier=com.jetbrains.pycharm, SHELL=/bin/bash, SECURITYSESSIONID=186f7, USER=aazhiry1, TMPDIR=/var/folders/by/pdgmdm4d6cd0pcl85wrh27vngtsnyj/T/, COMMAND_MODE=unix2003, LaunchInstanceID=FBE0022A-1CEC-4158-A628-0BF34E2E2BBF, PS1=(cmd_bl_311_2) , PYTHONDONTWRITEBYTECODE=1, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.IkiTKWZp9Q/Listeners, VIRTUAL_ENV=/Users/aazhiry1/venvs/cmd_bl_311_2, XPC_FLAGS=0x0, PYTHONUNBUFFERED=1, __CF_USER_TEXT_ENCODING=0x5FACD7D1:0x7:0x31, LOGNAME=aazhiry1, LC_CTYPE=ru_RU.UTF-8, XPC_SERVICE_NAME=application.com.jetbrains.pycharm.1134563.22015664, PWD=/Users/aazhiry1/venvs/cmd_bl_311_2/bin, HOME=/Users/aazhiry1, PIP_BUILD_TRACKER=/private/var/folders/by/pdgmdm4d6cd0pcl85wrh27vngtsnyj/T/pip-build-tracker-qzfticek, PYTHONNOUSERSITE=1, PYTHONPATH=/private/var/folders/by/pdgmdm4d6cd0pcl85wrh27vngtsnyj/T/pip-build-env-3i9wshe2/site, PEP517_BUILD_BACKEND=setuptools.build_meta
      building for target architecture: x86_64
      enabling SSE4.2 on compile
      enabling AES on compile
      building extension using Cython
      running bdist_wheel
      running build
      running build_ext
      skipping 'src/cityhash.cpp' Cython extension (up-to-date)
      skipping 'src/farmhash.cpp' Cython extension (up-to-date)
      skipping 'src/cityhashcrc.cpp' Cython extension (up-to-date)
      building 'cityhash' extension
      creating build
      creating build/temp.macosx-10.9-universal2-cpython-311
      creating build/temp.macosx-10.9-universal2-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Isrc -I/Users/aazhiry1/venvs/cmd_bl_311_2/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/city.cc -o build/temp.macosx-10.9-universal2-cpython-311/src/city.o -O3 -Wno-unused-value -Wno-unused-function -msse4.2 -maes
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -Isrc -I/Users/aazhiry1/venvs/cmd_bl_311_2/include -I/Library/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/cityhash.cpp -o build/temp.macosx-10.9-universal2-cpython-311/src/cityhash.o -O3 -Wno-unused-value -Wno-unused-function -msse4.2 -maes
      src/cityhash.cpp:4747:5: error: member access into incomplete type 'PyFrameObject' (aka '_frame')
          __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
          ^
      src/cityhash.cpp:452:62: note: expanded from macro '__Pyx_PyFrame_SetLineNumber'
        #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
                                                                   ^
      /Library/Frameworks/Python.framework/Versions/3.11/include/python3.11/pytypedefs.h:22:16: note: forward declaration of '_frame'
      typedef struct _frame PyFrameObject;
                     ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cityhash
ERROR: Could not build wheels for cityhash, which is required to install pyproject.toml-based projects

**Comment by HacKanCuBa** [comment]
It seems CPython 3.11 support [was dropped](https://github.com/escherba/python-cityhash/pull/72/files) for some reason, maybe something didn't work back then. Could we bring it back? 🥺

**Comment by tfrokt** [comment]
Different error, but might be related:
```
Failed to build clickhouse-cityhash
Installing collected packages: clickhouse-cityhash, ciso8601, tzdata, lz4, pytz-deprecation-shim, tzlocal, asynch
  Running setup.py install for clickhouse-cityhash ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for clickhouse-cityhash did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      running install
      /Users/<somepath>/.ve/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-arm64-cpython-311
      creating build/lib.macosx-13-arm64-cpython-311/clickhouse_cityhash
      copying clickhouse_cityhash/__init__.py -> build/lib.macosx-13-arm64-cpython-311/clickhouse_cityhash
      running build_ext
      building 'clickhouse_cityhash.cityhash' extension
      creating build/temp.macosx-13-arm64-cpython-311
      creating build/temp.macosx-13-arm64-cpython-311/src
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -Iinclude -I/Users/<somepath>/.ve/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/city.cc -o build/temp.macosx-13-arm64-cpython-311/src/city.o -O3 -Wno-unused-value -Wno-unused-function
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk -Iinclude -I/Users/<somepath>/.ve/include -I/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11 -c src/cityhash.cpp -o build/temp.macosx-13-arm64-cpython-311/src/cityhash.o -O3 -Wno-unused-value -Wno-unused-function
      src/cityhash.cpp:151:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> clickhouse-cityhash
```

**Comment by escherba** [comment]
Hello, this is the maintainer of the upstream `python-cityhash`. I just bumped this package to v0.4.3 which now includes wheels for Python 3.11. I do not control `clickhouse-cityhash` but can provide some limited support (Q/A). Please ping @xzkostyan first, however, as he is the maintainer of the latter.

**Comment by xzkostyan** [comment]
@tfrokt try latest master, until new version of clickhouse-cityhash will be published https://github.com/xzkostyan/clickhouse-cityhash/commit/112fa22f2ff0bcfeed827dbebacc5e50828f24a9
