### ISSUE TITLE
cityhash.CityHash64("uzumarket") return a value greater than INT64_MAX

### ISSUE THREAD

**Issue by GOGOYAO** [escherba/python-cityhash#87]
```
>>> import cityhash
>>> cityhash.CityHash64("1")
9304157803607034849
>>> cityhash.CityHash64("uzumarket")
10092950647370484876
```
In my opinion, `cityhash.CityHash64("uzumarket")` should return a value less than INT64_MAX.  Anyone help?

**Comment by escherba** [comment]
Thank you for the comment! The behavior of `CityHash64` mimics that of the Google's C library, which returns an _unsigned_ int64 type. While the value `10092950647370484876` is indeed too large to fit into `int64` it does fit into `uint64` type. Example:

```
>>> import numpy as np
>>> np.ulonglong(10092950647370484876)
10092950647370484876
>>> np.int64(10092950647370484876)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```
